# -*- coding: utf-8 -*-
"""viz_cereals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENSz6KUUaoN3aBqVV_f0ZEUrDLM2wZWG
"""

# Importing core libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

"""# **Content**

## Fields in the dataset:

   1. Name: Name of cereal
   1. mfr: Manufacturer of cereal
       * A = American Home Food Products
       * G = General Mills
       * K = Kelloggs
       * N = Nabisco
       * P = Post
       * Q = Quaker Oats
       * R = Ralston Purina 
   1. type:
        * cold
        * hot 
   1. calories: calories per serving
   1. protein: grams of protein
   1. fat: grams of fat
   1. sodium: milligrams of sodium
   1. fiber: grams of dietary fiber
   1. carbo: grams of complex carbohydrates
   1. sugars: grams of sugars
   1. potass: milligrams of potassium
   1. vitamins: vitamins and minerals - 0, 25, or 100, indicating the typical percentage of FDA recommended
   1. shelf: display shelf (1, 2, or 3, counting from the floor)
   1. weight: weight in ounces of one serving
   1. cups: number of cups in one serving
   

### Acknowledgements

These datasets have been gathered and cleaned up by Petra Isenberg, Pierre Dragicevic and Yvonne Jansen. The original source can be found here

This dataset has been converted to CSV

Inspiration

The rise of non-communicable disease (NCD) has been attributed to the poor nutrition in most of the common cerials at the market place.
Question:

1. Amount of Protein, Carbonhydrate and Fat for Each Cereals #LINE CHART AND FILLED AREA PLOT
1. Amount of Protein and Fiber for Each Cereal #SCATTER CHART
1. Amount of Calori in the Top 3 Cereal According to Rating Score #BAR PLOT
"""

# Importing dataset into pyhton
file_path = '/content/cereals.csv'
dataset = pd.read_csv(file_path)

# Displaying the dataset as is:
dataset_cereals=dataset
print(dataset)

# Droping colunms
dataset = dataset.drop('Cereal',axis=1)
print(dataset)

dataset.dtypes

# Amount of Protein, Carbohydrates and Fat for Each Cereals Hue = Type
g = sbn.PairGrid(dataset[['Protein','Carbohydrates','Fat','Type']],hue='Type',)
g.map(plt.scatter)
plt.show()

# Amount of Protein, Carbohydrates and Fat for Each Cereals Hue = Type
g = sbn.PairGrid(dataset[['Protein','Carbohydrates','Fat','Manufacturer']],hue='Manufacturer',)
g.map(plt.scatter)
plt.legend()
plt.show()

# Amount of Protein and Fiber for Each Cereal
plt.scatter(x='Protein',y='Fiber',data=dataset)
plt.show()

# Examing the different Nutrients and shelf placement
fig, axs = plt.subplots(3,3,constrained_layout=True)

axs[0, 0].bar(x='Shelf',height='Protein',data=dataset)
axs[0, 0].set_title('Protein', fontsize=10)

axs[0, 1].bar(x='Shelf',height='Fat',data=dataset)
axs[0, 1].set_title('Fat', fontsize=10)

axs[0, 2].bar(x='Shelf',height='Sodium',data=dataset)
axs[0, 2].set_title('Sodium', fontsize=10)

axs[1, 0].bar(x='Shelf',height='Fiber',data=dataset)
axs[1, 0].set_title('Fiber', fontsize=10)

axs[1, 1].bar(x='Shelf',height='Carbohydrates',data=dataset)
axs[1, 1].set_title('Carbohydrates', fontsize=10)

axs[1, 2].bar(x='Shelf',height='Sugars',data=dataset)
axs[1, 2].set_title('Sugars', fontsize=10)

axs[2, 0].bar(x='Shelf',height='Potassium',data=dataset)
axs[2, 0].set_title('Potassium', fontsize=10)

axs[2, 1].bar(x='Shelf',height='Vitamins',data=dataset)
axs[2, 1].set_title('Vitamins', fontsize=10)

axs[2, 2].bar(x='Shelf',height='Weight',data=dataset)
axs[2, 2].set_title('Weight', fontsize=10)
plt.show()

"""How many calories should breakfast provide?
This information can be found at https://www.nhs.uk/live-well/eat-well/healthy-breakfast-cereals/

A helpful rule of thumb to maintain a healthy weight is to follow the 400-600-600 approach.

That means having about:

    400kcal for breakfast (including any drinks and accompaniments)
    600kcal for lunch (including any drinks and accompaniments)
    600kcal for dinner (including any drinks and accompaniments) That leaves you with just enough left over to enjoy a few healthy drinks and snacks throughout the day. This advice is based on a woman's daily recommended calorie intake of 2,000kcal.

"You might get about 150kcal from a 40g serving of cereal," says Govindji. "You could add a medium sliced banana and 200ml of semi-skimmed milk, which altogether would provide about 350kcals.


Sugar, fat and salt levels

You can use the per 100g information on the nutrition label to identify breakfast cereals that are:

High in sugar, fat or salt

    high in sugar: more than 22.5g of total sugars per 100g
    high in fat: more than 17.5g of fat per 100g
    high in salt: more than 1.5g of salt per 100g

Low in sugar, fat or salt

    low in sugar: 5g of total sugars or less per 100g
    low in fat: 3g of saturated fat or less per 100g
    low in salt: 0.3g of salt or less per 100g
"""

dataset_cereals.dtypes

# Cereals Calories content in  respect to Breakfast Calories recommended by the NHS
plt.figure(figsize=[20,10])
plt.plot('Cereal','Calories',data=dataset_cereals,color='red',label='Cereal Sodium  Content')
plt.axhline(y=400,color='green',label='Reccomended Calories')
plt.xticks(rotation=90)
plt.legend()
plt.legend()
plt.show()

# Cereals with Low sugar
plt.figure(figsize=[20,10])
plt.plot('Cereal','Sugars',data=dataset_cereals,color='red',label='Cerial Sugar')
plt.axhline(y=5,color='green',label='Low Sugar')
plt.axhline(y=22.5,label='High Sugar')
plt.xticks(rotation=90)
plt.legend()
plt.show()

fig, ax = plt.subplots()
l1 = ax.plot('Cereal','Sugars',data=dataset_cereals,color='green')
l2 = ax.axhline(y=22.5,color='red')
l3 = ax.axhline(y=5)
ax.legend((l1,l2,l3),('Sugar content', 'High Sugar','Low Sugar'),loc='upper right', shadow=True)
plt.xticks(rotation=90)
plt.xlabel('Name of Cereal')
plt.ylabel('grams of sugars')
plt.show()

"""### low in fat: 3g of saturated fat or less per 100g
### high in fat: more than 17.5g of fat per 100g
"""

# Cereals Fat content in  respect to Low and Fat content as recommended by the NHS
plt.figure(figsize=[20,10])
plt.plot('Cereal','Fat',data=dataset_cereals,color='red',label='Cereal Fat Content')
plt.axhline(y=3,color='green',label='Low Fat')
plt.axhline(y=17.5,label='High Fat')
plt.xticks(rotation=90)
plt.legend()
plt.show()

"""low in salt: 0.3g of salt or less per 100g

high in salt: more than 1.5g of salt per 100g
"""

# Cereals Sodium content in  respect to Low and Fat content as recommended by the NHS
plt.figure(figsize=[20,10])
plt.plot('Cereal','Sodium',data=dataset_cereals,color='red',label='Cereal Sodium  Content')
plt.axhline(y=0.3,color='green',label='Low Sodium')
plt.axhline(y=1.5,label='High Sodium')
plt.xticks(rotation=90)
plt.legend()
plt.show()

"""Manufacturers use Different Cups for One Serving"""

sbn.relplot(x="Manufacturer",y='Cups', hue="Manufacturer", size="Weight",sizes=(40, 400), alpha=.5, palette="muted",height=6,data=dataset)
plt.show()

"""Lets plot a corelation plot and understand what features have a strong corelation to good ratings."""

corr = dataset.corr()
ax = sbn.heatmap(
    corr, 
    vmin=-1, vmax=1, center=0,
    cmap=sbn.diverging_palette(20, 220, n=200),
    square=True
)
ax.set_xticklabels(
    ax.get_xticklabels(),
    rotation=45,
    horizontalalignment='right'
)